version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    depends_on:
      - kafka
  
  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "5001:5000"
    volumes:
      - ./dashboard:/app

  frontend:
    container_name: frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    image: nginx:alpine

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  spark-streaming:
    build: ./streaming
    container_name: spark-streaming
    volumes:
      - ./streaming:/app
    depends_on:
      - kafka
    command: python /app/spark_streaming.py
